version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONPATH=/code
    volumes:
      # Mount source code for development (comment out for production)
      - ./backend/app:/code/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Database service (for future use with history storage)
  # database:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: sentiment_db
  #     POSTGRES_USER: sentiment_user
  #     POSTGRES_PASSWORD: sentiment_pass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: