name: Frontend CI/CD

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main, master ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Lint code
      run: |
        cd frontend
        npm run lint
    
    - name: Build application
      run: |
        cd frontend
        npm run build
    
    - name: Test build artifacts
      run: |
        cd frontend
        # Check if build was successful
        ls -la dist/
        
        # Basic checks on built files
        test -f dist/index.html || exit 1
        echo "✅ Build successful"

  # Uncomment and configure for deployment to Vercel/Netlify
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - uses: actions/checkout@v4
  #   
  #   - name: Set up Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '20'
  #       cache: 'npm'
  #       cache-dependency-path: frontend/package-lock.json
  #   
  #   - name: Install dependencies
  #     run: |
  #       cd frontend
  #       npm ci
  #   
  #   - name: Build for production
  #     run: |
  #       cd frontend
  #       npm run build
  #   
  #   - name: Deploy to Vercel
  #     # Add Vercel deployment action here
  #     run: echo "Deploy to Vercel"